# Generated by Django 6.0.1 on 2026-02-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('exchange', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'company_profiles',
            },
        ),
        migrations.CreateModel(
            name='StockCache',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('change', models.DecimalField(decimal_places=6, max_digits=20)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('previous_close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(max_length=50)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Cache',
                'verbose_name_plural': 'Stock Cache',
                'db_table': 'stock_cache',
            },
        ),
    ]
