# Generated by Django 6.0.1 on 2026-07-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16, unique=True)),
                ('cik', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('10-K', '10-K (Annual Report)'), ('10-Q', '10-Q (Quarterly Report)'), ('8-K', '8-K (Current Report)')], db_index=True, max_length=16)),
                ('accession_number', models.CharField(max_length=32, unique=True)),
                ('filed_date', models.DateField(db_index=True)),
                ('period_of_report', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source_url', models.URLField(max_length=512)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='filings.company')),
            ],
            options={
                'ordering': ['-filed_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='filings.filing')),
            ],
            options={
                'ordering': ['filing', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('char_start', models.IntegerField(default=0)),
                ('char_end', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('embedding_dim', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='filings.company')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='filings.filing')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='filings.section')),
            ],
            options={
                'ordering': ['filing', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['company', 'form_type', '-filed_date'], name='filings_fil_company_1bc375_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['filing', 'name'], name='filings_sec_filing__864a64_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['company', 'filing'], name='filings_chu_company_528f35_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['section'], name='filings_chu_section_514b24_idx'),
        ),
    ]
