# Generated by Django 6.0.1 on 2026-02-01 06:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_value', models.IntegerField()),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('buying_power', models.DecimalField(decimal_places=2, default=100000.0, max_digits=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=100000.0, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PREMIUM', 'Premium')], default='FREE', max_length=20)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('shares', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='users.userprofile')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=10)),
                ('target_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('enabled', models.BooleanField(default=True)),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='users.userprofile')),
            ],
            options={
                'db_table': 'price_alerts',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_price_alerts', models.BooleanField(default=True)),
                ('notify_trade_confirmations', models.BooleanField(default=True)),
                ('notify_weekly_report', models.BooleanField(default=False)),
                ('notify_market_news', models.BooleanField(default=True)),
                ('default_order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], default='MARKET', max_length=10)),
                ('confirm_trades', models.BooleanField(default=True)),
                ('show_profit_loss', models.BooleanField(default=True)),
                ('compact_mode', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light'), ('AUTO', 'Auto')], default='DARK', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.userprofile')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.userprofile')),
            ],
            options={
                'db_table': 'user_achievements',
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('shares', models.DecimalField(decimal_places=8, max_digits=20)),
                ('avg_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='users.userprofile')),
            ],
            options={
                'db_table': 'holdings',
                'unique_together': {('user', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('starred', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='users.userprofile')),
            ],
            options={
                'db_table': 'watchlist',
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
