# Generated by Django 6.0.1 on 2026-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='market',
            field=models.CharField(choices=[('US', 'United States'), ('IN', 'India (NSE/BSE)')], default='US', max_length=10),
        ),
    ]
