# Generated by Django 6.0.1 on 2026-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verification_enabled', models.BooleanField(default=False, help_text='When enabled, new users must verify their email before logging in.')),
                ('smtp_host', models.CharField(blank=True, default='', help_text='e.g. smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='Common ports: 587 (TLS), 465 (SSL), 25')),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption (recommended for port 587)')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (for port 465)')),
                ('smtp_from_email', models.EmailField(blank=True, default='', help_text='From address for outgoing emails', max_length=254)),
                ('smtp_from_name', models.CharField(blank=True, default='Open Papertrade', max_length=100)),
                ('frontend_url', models.URLField(default='http://localhost:3000', help_text='Frontend URL for email verification links')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
