# Generated by Django 6.0.1 on 2026-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_email_verification_and_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency the avg_cost is denominated in', max_length=3),
        ),
        migrations.AddField(
            model_name='trade',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency the price/total are denominated in', max_length=3),
        ),
    ]
