# Generated by Django 6.0.1 on 2026-02-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_currency_to_trade_and_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_buying_power',
            field=models.DecimalField(decimal_places=2, default=100000.0, help_text='Starting buying power for new users (e.g. 100000 for $100K or ₹1,00,000)', max_digits=20),
        ),
    ]
