# Generated by Django 6.0.1 on 2026-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(default='Intern', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
