# Generated by Django 6.0.1 on 2026-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_level_userprofile_rank_userprofile_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(default='Retail Trader', max_length=30),
        ),
    ]
