# Generated by Django 6.0.1 on 2026-02-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.CharField(blank=True, default='We are currently undergoing scheduled maintenance. Please check back soon.', help_text='Message displayed to users during maintenance.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='When enabled, all users see a maintenance page instead of the app.'),
        ),
    ]
