# Generated by Django 6.0.1 on 2026-02-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_sitesettings_maintenance_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_discord',
            field=models.URLField(blank=True, default='', help_text='Discord invite URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Support email shown during maintenance', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_github',
            field=models.URLField(blank=True, default='', help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_twitter',
            field=models.URLField(blank=True, default='', help_text='Twitter / X profile URL'),
        ),
    ]
