# Generated by Django 6.0.1 on 2026-02-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_buying_power',
            field=models.JSONField(blank=True, default=dict, help_text='Per-currency starting buying power, e.g. {"USD": 100000, "INR": 1000000, "EUR": 50000}'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_buying_power',
            field=models.DecimalField(decimal_places=2, default=100000.0, help_text='Fallback starting buying power when no currency-specific default is set.', max_digits=20),
        ),
    ]
