# Generated by Django 6.0.1 on 2026-02-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_transfer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
