# Generated by Django 6.0.1 on 2026-02-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_reset_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='recipient_currency',
            field=models.CharField(default='USD', help_text='Recipient currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_display_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount displayed in recipient currency', max_digits=20),
        ),
    ]
