# Generated by Django 6.0.1 on 2026-02-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_add_recipient_currency_to_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='exchange_rates',
            field=models.JSONField(blank=True, default=dict, help_text='Admin-set exchange rates vs USD, e.g. {"EUR": 0.84, "INR": 90.55, "GBP": 0.73}. Used when live API is unavailable.'),
        ),
    ]
