# Generated by Django 6.0.1 on 2026-04-16 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_exchange_rates_to_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], default='ACTIVE', max_length=7)),
                ('allocated_funds', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remaining_funds', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trade_delay', models.CharField(choices=[('NONE', 'None'), ('1H', '1 Hour'), ('6H', '6 Hours'), ('24H', '24 Hours')], default='NONE', max_length=4)),
                ('proportional_sizing', models.BooleanField(default=True)),
                ('max_trade_percent', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('copy_sells', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('copier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_following', to='users.userprofile')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_followers', to='users.userprofile')),
            ],
            options={
                'db_table': 'copy_relationships',
                'ordering': ['-created_at'],
                'unique_together': {('copier', 'leader')},
            },
        ),
        migrations.CreateModel(
            name='CopyTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=8)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('source_symbol', models.CharField(max_length=20)),
                ('source_trade_type', models.CharField(max_length=4)),
                ('source_shares', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('copy_shares', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('copy_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('copy_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_trades', to='users.copyrelationship')),
                ('executed_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_source', to='users.trade')),
                ('source_trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_as', to='users.trade')),
            ],
            options={
                'db_table': 'copy_trades',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='TraderFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed_delay', models.CharField(choices=[('NONE', 'None'), ('1H', '1 Hour'), ('24H', '24 Hours')], default='1H', max_length=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.userprofile')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.userprofile')),
            ],
            options={
                'db_table': 'trader_follows',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'leader')},
            },
        ),
    ]
